<?php
$valueOptions = [];
$pages = $this->api()->search('faceted_browse_pages', ['site_id' => $site->id()])->getContent();
foreach ($pages as $page) {
    $valueOptions[$page->id()] = $page->title();
}
$element = new \Laminas\Form\Element\Select('page_id');
$element->setValueOptions($valueOptions)
    ->setEmptyOption($this->translate('Select a page'))
    ->setValue($data['page_id'] ?? null)
    ->setAttributes([
        'data-name' => 'page_id',
        'required' => true,
    ]);
?>
<label><?php echo $this->translate('Type'); ?> <input type="text" value="<?php echo $this->escapeHtml($this->translate($link->getName())); ?>" disabled></label>
<label class="required"><?php echo $this->translate('Label'); ?> <input type="text" data-name="label" value="<?php echo $this->escapeHtml($data['label'] ?? null); ?>" required></label>
<label class="required"><?php echo $this->translate('Page'); ?> <?php echo $this->formElement($element); ?></label>
