<?php
use FacetedBrowse\Form\PageForm;

$this->htmlElement('body')->appendAttribute('class', 'faceted-browse page browse');
?>

<?php echo $this->pageTitle($this->translate('Pages'), 1, $this->translate('Faceted Browse')); ?>

<?php if ($this->userIsAllowed('FacetedBrowse\Api\Adapter\FacetedBrowsePageAdapter', 'create')): ?>
<div id="page-actions">
    <div id="page-action-menu">
        <?php echo $this->hyperlink($this->translate('Add new page'), $this->url('admin/site/slug/faceted-browse-page', ['action' => 'add'], true), ['class' => 'button']); ?>
    </div>
</div>
<?php endif; ?>

<div class="breadcrumbs">
    <?php echo $this->translate('Pages'); ?>
</div>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
    [
        'label' => $this->translate('Date created'),
        'value' => 'created',
    ],
    [
        'label' => $this->translate('Title'),
        'value' => 'title',
    ],
]); ?>
</div>

<?php if ($pages): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Page'); ?></th>
            <th><?php echo $this->translate('Resource type'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Created'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($pages as $page): ?>
    <?php $owner = $page->owner(); ?>
        <tr>
            <td>
                <?php echo $page->title(); ?>
                <ul class="actions">
                    <?php if ($page->userIsAllowed('update')): ?>
                    <li><?php echo $page->link('', 'edit', ['class' => 'fa fa-pencil-alt', 'title' => $this->translate('Edit')]) ?></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td><?php echo $this->translate(PageForm::RESOURCE_TYPES[$page->resourceType()]); ?></td>
            <td><?php echo $owner ? $owner->link($owner->name()) : ''; ?></td>
            <td><?php echo $this->i18n()->dateFormat($page->created()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="show-details" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>
<div class="no-resources">
    <?php if ($this->userIsAllowed('FacetedBrowse\Api\Adapter\FacetedBrowsePageAdapter', 'create')): ?>
    <p><?php echo sprintf(
        $this->translate('No pages found. %s'),
        $this->hyperlink($this->translate('Add a new page.'), $this->url('admin/site/slug/faceted-browse-page', ['action' => 'add'], true))
    ); ?></p>
    <?php else: ?>
    <p><?php echo $this->translate('No pages found.'); ?></p>
    <?php endif; ?>
</div>
<?php endif; ?>
