<?php
use Laminas\Form\Element\Hidden;
?>
<li class="category value row">
    <span class="sortable-handle"></span>
    <span class="category-name-display"><?php echo $category['o:name']; ?></span>
    <ul class="actions">
        <li><?php echo $this->hyperlink('', $this->url('admin/site/slug/faceted-browse-category-id', ['action' => 'edit', 'category-id' => $category['o:id']], true), [
            'class' => 'o-icon-edit category-edit',
            'title' => $this->translate('Edit category'),
        ]); ?></li>
    </ul>
    <?php
    $categoryInput = (new Hidden(sprintf('o-module-faceted_browse:category[%s][o:id]', $index)))
        ->setValue($category['o:id'])
        ->setAttribute('class', 'category-id');
    echo $this->formHidden($categoryInput);
    ?>
</li>
