<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/site-admin/faceted-browse.css', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/site-admin/page-form.js', 'FacetedBrowse'));

if ($page) {
    $this->htmlElement('body')->appendAttribute('class', 'faceted-browse page edit browse');
} else {
    $this->htmlElement('body')->appendAttribute('class', 'faceted-browse page add browse');
}
$form->prepare();
?>
<?php if ($page): ?>
<?php echo $this->pageTitle($this->translate('Edit Page'), 1, $this->translate('Faceted Browse'), $page->title()); ?>
<?php else: ?>
<?php echo $this->pageTitle($this->translate('Add Page'), 1, $this->translate('Faceted Browse')); ?>
<?php endif; ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php if ($page): ?>
    <a href="#" id="delete-button" class="delete button"><?php echo $this->translate('Delete'); ?></a>
    <?php endif; ?>
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/site/slug/faceted-browse-page', ['action' => 'browse'], true), ['class' => 'button']); ?>
    <div id="page-action-menu">
        <a href="#" class="button expand" aria-label="<?php echo $this->translate('Expand'); ?>" title="<?php echo $this->translate('Expand'); ?>">
        <?php echo $this->translate('Save and&hellip;'); ?></a>
        <ul class="collapsible">
            <li><input type="submit" name="submit_save" value="<?php echo $this->escapeHtml($this->translate('Return to pages')); ?>"></li>
            <li><input type="submit" name="submit_save_remain" value="<?php echo $this->escapeHtml($this->translate('Stay on this page')); ?>"></li>
        </ul>
    </div>
</div>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Pages'), $this->url('admin/site/slug/faceted-browse-page', ['action' => 'browse'], true)); ?>
    <div class="separator"></div>
    <?php echo $page ? $this->translate('Page edit') : $this->translate('Page add'); ?>
</div>

<fieldset>
    <?php echo $this->formRow($form->get('o:title')); ?>
    <?php echo $this->formRow($form->get($page ? 'resource_type' : 'o-module-faceted_browse:resource_type')); ?>
</fieldset>

<?php if ($page): ?>
<fieldset>
    <legend><?php echo $this->translate('Categories'); ?></legend>
    <?php echo $this->hyperlink($this->translate('Add category'), $this->url('admin/site/slug/faceted-browse-category', ['action' => 'add'], true), ['class' => 'button']); ?>
    <ul id="categories" class="sortable-list">
        <?php foreach ($page->categories() as $index => $category): ?>
        <?php echo $this->partial('category-row.phtml', ['index' => $index, 'category' => $category->jsonSerialize()]); ?>
        <?php endforeach; ?>
    </ul>
</fieldset>
<?php endif; ?>

<?php echo $this->formHidden($form->get('csrf')); ?>
<?php echo $this->form()->closeTag(); ?>

<?php if ($page): ?>
<?php echo $this->deleteConfirm($page, 'page'); ?>
<?php endif; ?>
