<?php
$form->prepare();
$facetType = $this->facetedBrowse()->getFacetType($facetType);
?>
<div class="meta-group">
    <h4><?php echo $this->translate('Facet type'); ?></h4>
    <div class="value"><?php echo $facetType->getLabel(); ?></div>
</div>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('facet_type')); ?>
<?php echo $this->formRow($form->get('facet_name')); ?>
<?php echo $facetType->renderDataForm($this, $facetData); ?>
<?php if ($this->facetedBrowse()->facetTypeIsKnown($facetType)): ?>
<?php echo $this->formElement($form->get('facet_set')); ?>
<?php endif; ?>
<?php echo $this->form()->closeTag(); ?>
