<ul>
    <?php foreach ($classes as $class): ?>
    <li>
        <label>
            <input
                class="by-class"
                type="radio"
                name="<?php echo sprintf('by_class_%s', $facet->id()); ?>"
                data-class-id="<?php echo $this->escapeHtml($class->id()); ?>">
                <?php echo $class->label(); ?>
        </label>
    </li>
    <?php endforeach; ?>
</ul>
