<ul>
    <?php foreach ($values as $key => $value): ?>
    <?php
    $dataPropertyId = $facet->data('property_id');
    $dataValue = $key;
    if (in_array($facet->data('query_type'), ['ex', 'nex'])) {
        $dataPropertyId = $key;
    }
    ?>
    <li>
        <label>
            <input
                class="by-value"
                type="<?php echo ('multiple' === $facet->data('select_type')) ? 'checkbox' : 'radio'; ?>"
                name="<?php echo sprintf('by_value_%s', $facet->id()); ?>"
                data-property-id="<?php echo $this->escapeHtml($dataPropertyId); ?>"
                data-value="<?php echo $this->escapeHtml($dataValue); ?>">
                <?php echo $value; ?>
        </label>
    </li>
    <?php endforeach; ?>
</ul>
