<?php if ($singleSelect): ?>
<?php echo $this->formElement($singleSelect); ?>
<?php else: ?>
<?php
$truncate = $facet->data('truncate_item_sets');
if ('single_list' === $facet->data('select_type') && $truncate) {
    $truncate++;
}
?>
<ul class="select-list" id="select-list-<?php echo $facet->id(); ?>" data-truncate-list-items="<?php echo $this->escapeHtml($truncate); ?>">
    <?php if ('single_list' === $facet->data('select_type')): ?>
    <li class="select-list-item">
        <label>
            <input
                class="item-set"
                type="radio"
                name="<?php echo sprintf('item_set_%s', $facet->id()); ?>"
                data-item-set-id="">
                <?php echo $this->translate('All'); ?>
        </label>
    </li>
    <?php endif; ?>
    <?php foreach ($itemSets as $itemSet): ?>
    <li class="select-list-item">
        <label>
            <input
                class="item-set"
                type="<?php echo ('multiple_list' === $facet->data('select_type')) ? 'checkbox' : 'radio'; ?>"
                name="<?php echo sprintf('item_set_%s', $facet->id()); ?>"
                data-item-set-id="<?php echo $this->escapeHtml($itemSet->id()); ?>">
                <?php echo $itemSet->title(); ?>
        </label>
    </li>
    <?php endforeach; ?>
</ul>
<button type="button" class="select-list-expand" aria-expanded="false" aria-controls="select-list-<?php echo $facet->id(); ?>" style="display: none;"><?php echo $this->translate('See more'); ?> <span class="select-list-hidden-count"></span></button>
<button type="button" class="select-list-collapse" aria-expanded="true" aria-controls="select-list-<?php echo $facet->id(); ?>" style="display: none;"><?php echo $this->translate('See less'); ?></button>
<?php endif; ?>
