<ul>
    <?php foreach ($values as $value): ?>
    <li>
        <label>
            <input
                class="property-literal"
                type="<?php echo ('multiple' === $facet->data('select_type')) ? 'checkbox' : 'radio'; ?>"
                name="<?php echo sprintf('property_literal_%s', $facet->id()); ?>"
                data-value="<?php echo $this->escapeHtml($value); ?>">
                <?php echo $value; ?>
        </label>
    </li>
    <?php endforeach; ?>
</ul>
