<?php if ($textInput): ?>
<?php echo $this->formElement($textInput); ?>
<?php elseif ($singleSelect): ?>
<?php echo $this->formElement($singleSelect); ?>
<?php else: ?>
<ul class="value-select-list">
    <?php
    $index = 1;
    foreach ($values as $key => $value):
    ?>
    <?php
    $dataPropertyId = $facet->data('property_id');
    $dataValue = $key;
    if (in_array($facet->data('query_type'), ['ex', 'nex'])) {
        $dataPropertyId = $key;
    }
    ?>
    <li class="value-select-list-item"<?php echo (10 < $index) ? ' style="display: none;"' : ''; ?>>
        <label>
            <input
                class="value"
                type="<?php echo ('multiple_list' === $facet->data('select_type')) ? 'checkbox' : 'radio'; ?>"
                name="<?php echo sprintf('value_%s', $facet->id()); ?>"
                data-property-id="<?php echo $this->escapeHtml($dataPropertyId); ?>"
                data-value="<?php echo $this->escapeHtml($dataValue); ?>">
                <?php echo $value; ?>
        </label>
    </li>
    <?php
    $index++;
    endforeach;
    ?>
</ul>
<?php if (10 < count($values)): ?>
<a href="" class="value-select-list-expand"><?php echo $this->translate('See more'); ?></a>
<a href="" class="value-select-list-collapse" style="display: none;"><?php echo $this->translate('See less'); ?></a>
<?php endif; ?>
<?php endif; ?>
