<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
?>
<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <?php
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
    $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
    ?>
    <li class="item resource">
        <?php
            $thumbnailType = $page->thumbnailType() ?: 'medium';
            $linkContent = sprintf(
                '%s<span class="resource-name">%s</span>',
                $thumbnail($item, $thumbnailType),
                $escape($heading)
            );
            echo $item->linkRaw($linkContent, null, ['class' => 'resource-link']);
        ?>
        <?php if ($body): ?>
        <div class="description"><?php echo $this->escapeHtml($body); ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
