<?php echo $this->searchFilters(); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <input type="text" value="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $query, 'force_canonical' => true], true)); ?>">
    <?php echo $this->sortSelector([
        [
            'label' => $this->translate('Title'),
            'value' => 'title'
        ],
        [
            'label' => $this->translate('Identifier'),
            'value' => 'dcterms:identifier'
        ],
        [
            'label' => $this->translate('Created'),
            'value' => 'created'
        ],
    ]); ?>
</div>
<ul>
    <?php foreach ($items as $item): ?>
    <li><?php echo $item->linkPretty(); ?></li>
    <?php endforeach; ?>
</ul>
<?php echo $this->pagination(); ?>
