<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <a href="#" class="permalink button" data-url="<?php echo $this->escapeHtml($this->url(null, ['action' => 'page'], ['force_canonical' => true], true)); ?>"><span class="default"><?php echo $this->translate('Copy permalink'); ?></span><span class="success"><?php echo $this->translate('Copied!'); ?></span></a>
    <?php echo $this->sortSelector($sortings); ?>
</div>
<?php if ($items): ?>
<?php echo $this->partial($columns ? 'browse-items-columns' : 'browse-items-default'); ?>
<?php else: ?>
<p><?php echo $this->translate('There are no results.'); ?></p>
<?php endif; ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>
