<table class="tablesaw tablesaw-swipe" data-tablesaw-mode="swipe">
    <thead>
        <tr>
            <?php foreach ($columns as $column): ?>
            <th><?php echo $column->name(); ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
        <tr>
            <?php foreach ($columns as $column): ?>
            <td><?php echo $column->content($item); ?></td>
            <?php endforeach; ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
    jQuery(document).ready(function () {
        Tablesaw.init();
    });
</script>
