<?php $categories = $page->categories(); ?>
<?php if (0 === count($categories)): ?>
<h4><?php echo $this->translate('Browse'); ?></h4>
<div><?php echo $this->translate('There are no categories to browse.'); ?></div>
<?php elseif (1 === count($categories)): ?>
<?php echo $this->partial('facets', ['category' => current($categories), 'hideBack' => true]); ?>
<?php else: ?>
<h4><?php echo $this->translate('Browse'); ?></h4>
<ul id="categories">
    <?php foreach ($page->categories() as $category): ?>
    <li>
        <?php echo $this->hyperlink($category->name(), null, [
            'class' => 'category',
            'data-category-id' => $category->id(),
            'data-category-query' => $category->query(),
        ]); ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
