<?php $categories = $page->categories(); ?>
<h4><?php echo $this->translate('Browse'); ?></h4>
<?php if ($categories): ?>
<ul id="categories">
    <?php foreach ($categories as $category): ?>
    <li>
        <?php echo $this->hyperlink($category->name(), null, [
            'class' => 'category',
            'data-category-id' => $category->id(),
            'data-category-query' => $category->query(),
        ]); ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php else: ?>
<div><?php echo $this->translate('There are no categories to browse.'); ?></div>
<?php endif; ?>
