<button id="section-sidebar-modal-close" class="close-button" aria-label="<?php echo $this->escapeHtml($this->translate('Close')); ?>" aria-labelledby="section-sidebar-modal-close section-sidebar" type="button">
  <span aria-hidden="true" class="close-glyph"></span>
</button>
<div class="sr-only" id="facet-modal-description">
    This is a dialog window which overlays the main content of the page. The modal begins with a fieldset called <?php echo $category->name(); ?>. Pressing the Close Modal button at the top right of the modal will close the modal and bring you back to where you were on the page.
</div>
<?php echo $this->hyperlink($this->translate('Back'), [], ['id' => 'categories-return', 'class' => 'button']); ?>
<fieldset class="facets-container">
    <legend><?php echo $category->name(); ?></legend>
    <?php
    $helperText = $category->helperText();
    $helperTextButtonLabel = $category->helperTextButtonLabel();
    if ('' === trim($helperTextButtonLabel)) {
        $helperTextButtonLabel = $this->translate('Instructions');
    }
    ?>
    <?php if ($helperText): ?>
    <a id="helper-text-expand-collapse" class="button collapse" href="#"" aria-expanded="false"><?php echo $this->escapeHtml($helperTextButtonLabel); ?> </a>
    <div id="helper-text" class="collapsible" aria-labelledby="helper-text-expand-collapse"><?php echo $category->helperText(); ?></div>
    <?php endif; ?>
    <div id="facets"
        data-category-id="<?php echo $this->escapeHtml($category->id()); ?>"
        data-category-query="<?php echo $this->escapeHtml($category->query()); ?>">
        <?php foreach ($category->facets() as $facet): ?>
        <?php if ($this->facetedBrowse()->facetIsKnown($facet)): ?>
        <fieldset class="facet"
            data-facet-id="<?php echo $this->escapeHtml($facet->id()); ?>"
            data-facet-type="<?php echo $this->escapeHtml($facet->type()); ?>"
            data-facet-data="<?php echo $this->escapeHtml(json_encode($facet->data())); ?>">
            <legend><?php echo $facet->name(); ?></legend>
            <?php echo $this->facetedBrowse()->renderFacet($facet); ?>
        </fieldset>
        <?php endif; ?>
        <?php endforeach; ?>
    </div>
</fieldset>
