<?php echo $this->hyperlink($this->translate('Back'), [], ['id' => 'categories-return', 'class' => 'button']); ?>
<fieldset class="facets-container">
    <legend><?php echo $category->name(); ?></legend>
    <div class="facets"
        data-category-id="<?php echo $this->escapeHtml($category->id()); ?>"
        data-category-query="<?php echo $this->escapeHtml($category->query()); ?>">
        <?php foreach ($category->facets() as $facet): ?>
        <fieldset class="facet"
            data-facet-id="<?php echo $this->escapeHtml($facet->id()); ?>"
            data-facet-type="<?php echo $this->escapeHtml($facet->type()); ?>"
            data-facet-data="<?php echo $this->escapeHtml(json_encode($facet->data())); ?>">
            <legend><?php echo $facet->name(); ?></legend>
            <?php echo $this->facetedBrowse()->renderFacet($facet); ?>
        </fieldset>
        <?php endforeach; ?>
    </div>
</fieldset>
