<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/site/page.css', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('js/site/page.js', 'FacetedBrowse'));

$this->htmlElement('body')->appendAttribute('class', 'faceted-browse-page');
$this->pageTitle($page->title(), 2);
?>

<div id="section-sidebar"
    data-categories-url="<?php echo $this->escapeHtml($this->url(null, ['action' => 'categories'], true)); ?>">
</div>

<div id="section-content"
    data-browse-url="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
</div>
