<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/site/page.css', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('js/site/page.js', 'FacetedBrowse'));
$this->facetedBrowse()->prepareFacets();

$this->htmlElement('body')->appendAttribute('class', 'faceted-browse-page');
$this->pageTitle($page->title(), 2);
?>

<div id="container" style="display: flex"
    data-url-categories="<?php echo $this->escapeHtml($this->url(null, ['action' => 'categories'], true)); ?>"
    data-url-facets="<?php echo $this->escapeHtml($this->url(null, ['action' => 'facets'], true)); ?>"
    data-url-browse="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>"
>
    <div id="section-sidebar" style="width: 30%;"></div>
    <div id="section-content" style="width: 70%;"></div>
</div>
