<?php echo $heading; ?>

<table class="faceted-results tablesaw tablesaw-swipe">
    <thead>
        <tr>
            <?php foreach ($columns as $column): ?>
            <th><?php echo $column->name(); ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
        <tr>
            <?php foreach ($columns as $column): ?>
            <td><?php echo $column->content($item); ?></td>
            <?php endforeach; ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $linkOut; ?>
