<?php 
$this->headLink()->appendStylesheet($this->assetUrl('css/site/page.css', 'FacetedBrowse'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/tablesaw/tablesaw.css', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('vendor/tablesaw/tablesaw.jquery.js', 'FacetedBrowse'));
?>

<?php echo $heading; ?>

<?php if ($items): ?>
<?php echo $this->partial($columns
    ? 'faceted-browse/site/page/browse-items-columns'
    : 'faceted-browse/site/page/browse-items-default'); ?>
<?php endif; ?>

<?php echo $linkOut; ?>
