<?php
$this->htmlElement('body')->appendAttribute('class', 'faceted-browse category browse');
?>

<?php echo $this->pageTitle($this->translate('Categories'), 1, $this->translate('Faceted Browse')); ?>

<?php if ($this->userIsAllowed('FacetedBrowse\Api\Adapter\FacetedBrowseCategoryAdapter', 'create')): ?>
<div id="page-actions">
    <div id="page-action-menu">
        <?php echo $this->hyperlink($this->translate('Add new category'), $this->url('admin/site/slug/faceted-browse', ['action' => 'add'], true), ['class' => 'button']); ?>
    </div>
</div>
<?php endif; ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
    [
        'label' => $this->translate('Date created'),
        'value' => 'created',
    ],
    [
        'label' => $this->translate('Name'),
        'value' => 'name',
    ],
]); ?>
</div>

<?php if ($categories): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Category'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Created'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($categories as $category): ?>
    <?php $owner = $category->owner(); ?>
        <tr>
            <td>
                <?php echo $category->name(); ?>
                <ul class="actions">
                    <?php if ($category->userIsAllowed('update')): ?>
                    <li><?php echo $category->link('', 'edit', ['class' => 'fa fa-pencil-alt', 'title' => $this->translate('Edit')]) ?></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td><?php echo $owner ? $owner->link($owner->name()) : ''; ?></td>
            <td><?php echo $this->i18n()->dateFormat($category->created()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="show-details" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>
<div class="no-resources">
    <?php if ($this->userIsAllowed('FacetedBrowse\Api\Adapter\FacetedBrowseCategoryAdapter', 'create')): ?>
    <p><?php echo sprintf(
        $this->translate('No categories found. %s'),
        $this->hyperlink($this->translate('Add a new category.'), $this->url('admin/site/slug/faceted-browse', ['action' => 'add'], true))
    ); ?></p>
    <?php else: ?>
    <p><?php echo $this->translate('No categories found.'); ?></p>
    <?php endif; ?>
</div>
<?php endif; ?>
