<?php
$this->trigger('view.faceted_browse.category_form');

$this->headLink()->appendStylesheet($this->assetUrl('css/site-admin/faceted-browse.css', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/faceted-browse.js', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('js/site-admin/category-form.js', 'FacetedBrowse'));
$this->facetedBrowse()->prepareDataForms();
$this->ckEditor();

if ($category) {
    $this->htmlElement('body')->appendAttribute('class', 'faceted-browse category edit browse');
} else {
    $this->htmlElement('body')->appendAttribute('class', 'faceted-browse category add browse');
}
$form->prepare();
?>
<?php if ($category): ?>
<?php echo $this->pageTitle($this->translate('Edit Category'), 1, $this->translate('Faceted Browse'), $page->title()); ?>
<?php else: ?>
<?php echo $this->pageTitle($this->translate('Add Category'), 1, $this->translate('Faceted Browse'), $page->title()); ?>
<?php endif; ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php if ($category): ?>
    <a href="#" id="delete-button" class="delete button"><?php echo $this->translate('Delete'); ?></a>
    <?php endif; ?>
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/site/slug/faceted-browse-page-id', ['action' => 'edit'], true), ['class' => 'button']); ?>
    <div class="page-action-menu">
        <a href="#" class="button expand" aria-label="<?php echo $this->translate('Expand'); ?>" title="<?php echo $this->translate('Expand'); ?>">
        <?php echo $this->translate('Save and&hellip;'); ?></a>
        <ul class="collapsible">
            <li><input type="submit" name="submit_save" value="<?php echo $this->escapeHtml($this->translate('Return to page')); ?>"></li>
            <li><input type="submit" name="submit_save_remain" value="<?php echo $this->escapeHtml($this->translate('Stay on this category')); ?>"></li>
        </ul>
    </div>
</div>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Pages'), $this->url('admin/site/slug/faceted-browse-page', ['action' => 'browse'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Page edit'), $this->url('admin/site/slug/faceted-browse-page-id', ['action' => 'edit'], true)); ?>
    <div class="separator"></div>
    <?php echo $category ? $this->translate('Category edit') : $this->translate('Category add'); ?>
</div>

<?php if ($category): ?>
<h3><?php echo $this->escapeHtml($category->name()); ?></h3>
<?php endif; ?>

<fieldset>
    <?php echo $this->formRow($form->get('o:name')); ?>
    <?php echo $this->formRow($form->get('o:query')); ?>
    <?php echo $this->formRow($form->get('o-module-faceted_browse:sort_by')); ?>
    <?php echo $this->formRow($form->get('o-module-faceted_browse:sort_order')); ?>
    <?php echo $this->formRow($form->get('o-module-faceted_browse:helper_text')); ?>
    <?php echo $this->formRow($form->get('o-module-faceted_browse:helper_text_button_label')); ?>
    <?php echo $this->formRow($form->get('o-module-faceted_browse:value_facet_mode')); ?>
</fieldset>

<fieldset>
    <legend><?php echo $this->translate('Facets'); ?></legend>
    <?php echo $this->formSelect($form->get('facet_type')); ?>
    <button type="button" id="facet-add-button" disabled><?php echo $this->translate('Add'); ?></button>
    <ul id="facets"
        class="sortable-list"
        data-facet-row-url="<?php echo $this->escapeHtml($this->url('admin/site/slug/faceted-browse-category', ['action' => 'facet-row'], true)); ?>"
        data-facet-form-url="<?php echo $this->escapeHtml($this->url('admin/site/slug/faceted-browse-category', ['action' => 'facet-form'], true)); ?>">
        <?php if ($category): ?>
        <?php foreach ($category->facets() as $index => $facet): ?>
        <?php echo $this->partial('facet-row.phtml', ['index' => $index, 'facet' => $facet->jsonSerialize()]); ?>
        <?php endforeach; ?>
        <?php endif; ?>
    </ul>
</fieldset>

<fieldset>
    <legend><?php echo $this->translate('Columns'); ?></legend>
    <?php echo $this->formSelect($form->get('column_type')); ?>
    <button type="button" id="column-add-button" disabled><?php echo $this->translate('Add'); ?></button>
    <ul id="columns"
        class="sortable-list"
        data-column-row-url="<?php echo $this->escapeHtml($this->url('admin/site/slug/faceted-browse-category', ['action' => 'column-row'], true)); ?>"
        data-column-form-url="<?php echo $this->escapeHtml($this->url('admin/site/slug/faceted-browse-category', ['action' => 'column-form'], true)); ?>">
        <?php if ($category): ?>
        <?php foreach ($category->columns() as $index => $column): ?>
        <?php echo $this->partial('column-row.phtml', ['index' => $index, 'column' => $column->jsonSerialize()]); ?>
        <?php endforeach; ?>
        <?php endif; ?>
    </ul>
</fieldset>

<?php echo $this->formHidden($form->get('csrf')); ?>
<?php echo $this->form()->closeTag(); ?>

<div id="facet-sidebar" class="sidebar">
    <div class="sidebar-content">
        <div id="facet-form-container"></div>
    </div>
</div>

<div id="column-sidebar" class="sidebar">
    <div class="sidebar-content">
        <div id="column-form-container"></div>
    </div>
</div>

<?php if ($category): ?>
<?php echo $this->deleteConfirm($category, 'category'); ?>
<?php endif; ?>
