<?php if ($rows): ?>
<table>
    <thead>
        <tr>
            <th><?php echo $this->translate('Available'); ?></th>
            <th><?php echo $this->translate('Count'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $row): ?>
        <tr>
            <td><?php echo $row['label']; ?></td>
            <td><?php echo $row['has_count']; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<p><?php echo $this->translate('There are no results.'); ?></p>
<?php endif; ?>
