<?php if ($rows): ?>
<button id="add-all" type="button"><?php echo $this->translate('Add all'); ?></button>
<table id="show-all-table" data-rows="<?php echo $this->escapeHtml(json_encode($rows)); ?>">
    <thead>
        <tr>
            <th><?php echo $this->translate('Available'); ?></th>
            <th><?php echo $this->translate('Count'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $row): ?>
        <tr>
            <td><?php echo $this->escapeHtml($row['label']); ?></td>
            <td><?php echo $row['has_count']; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<p><?php echo $this->translate('There are no results.'); ?></p>
<?php endif; ?>
