<?php echo $this->formRow($elementPropertyId); ?>
<?php echo $this->formRow($elementQueryType); ?>
<?php echo $this->formRow($elementSelectType); ?>
<?php echo $this->formRow($elementValues); ?>
<p><input type="checkbox" id="value-literal-show-all-values"> <?php echo $this->translate('Show all available values of the selected property.'); ?></p>
<table id="value-literal-all-values" data-values-url="<?php echo $this->escapeHtml($this->url(null, ['action' => 'value-literal-values'], true)) ?>"></table>
