<?php echo $this->formRow($elementPropertyId); ?>
<?php echo $this->formRow($elementSelectType); ?>
<?php echo $this->formRow($elementQueryType); ?>
<?php echo $this->formRow($elementTruncateValues); ?>
<?php echo $this->formRow($elementValues); ?>
<?php echo $this->partial('show-all', [
    'label' => $this->translate('Show all available values.'),
    'url' => $this->url(null, ['action' => 'value-values'], true),
    'queryParams' => [
        'property_id' => '#value-property-id',
        'query_type' => '#value-query-type',
    ],
]); ?>
