<?php echo $this->formRow($elementPropertyId); ?>
<?php echo $this->formRow($elementSelectType); ?>
<?php echo $this->formRow($elementQueryType); ?>
<?php echo $this->formRow($elementTruncateValues); ?>
<?php echo $this->formRow($elementValues); ?>
<?php echo $this->partial('show-all', [
    'label' => $this->translate('Show available values'),
    'facetType' => $facetType,
    'queryParams' => [
        'facet_data[property_id]' => '#value-property-id',
        'facet_data[query_type]' => '#value-query-type',
    ],
    'addAll' => ['target' => '#value-values', 'mode' => 'textarea'],
]); ?>
